{% set name = "solders" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kevinheavey/solders/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1e31c0ab7687c8c9bb19bcbd9863ba7257590127d69ac3f4a091777a9cb9594b

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make  # [unix]
    - m2-make  # [not unix]
    - perl  # [not unix]
  host:
    - maturin >=1.8.1,<1.9
    - poetry
    - python
    - pip
    - setuptools-rust
  run:
    - jsonalias =0.1.1
    - python
    - typing_extensions

test:
  imports:
    - solders
  requires:
    - based58
    - mnemonic
    - pip
    - pybip39
    - pytest
    - pytest-asyncio
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/kevinheavey/solders
  summary: 'solders is a high-performance Python toolkit for Solana'
  description: |
    solders is a high-performance Python toolkit for Solana, written in Rust. It provides robust
    solutions to the following problems:
       - Core SDK stuff: keypairs, pubkeys, signing and serializing transactions - that sort of thing.
       - RPC stuff: building requests and parsing responses (no networking stuff - if you want help with that,
    solana-py is your friend).
       - Integration testing stuff: the solders.bankrun module is an alternative to solana-test-validator
    that's much more convenient and much faster. It's based on solana-program-test if you know that is.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://kevinheavey.github.io/solders/

extra:
  recipe-maintainers:
    - MementoRC
